# Uncomment the next line to define a global platform for your project
 platform :ios, '18.0'

target 'FinancialControl' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Router', :git => 'https://github.com/TiagoLinharess/app-ios-financial-control-v2.git', :branch => 'main'
  #pod 'Router', :path => '~/Documents/ProjetosPessoais/app-ios-financial-control-v2'
end
