name: FinancialControl

options:
  bundleIdPrefix: com.financial.control
  minimumXcodeGenVersion: 16.0
  generateEmptyDirectories: true
  plataform: iOS
  deploymentTarget:
    iOS: 18.0
    macOS: 15.0
    visionOS: 2.0
  postGenCommand: pod install

settings:
  base:
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    CODE_SIGN_STYLE: Automatic

targets:
  FinancialControl:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources: 
      - FinancialControl
    settings:
      base:
        ENABLE_BITCODE: NO
        PRODUCT_BUNDLE_IDENTIFIER: com.financial.control.app
        PRODUCT_NAME: FinancialControl
        ENABLE_PREVIEWS: YES
        DEVELOPMENT_ASSET_PATHS: "\"FinancialControl/Preview Content\""
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    info:
      path: FinancialControl/Info.plist
      properties:
        UIStatusBarStyle: UIStatusBarStyleLightContent
        LSApplicationCategoryType: public.app-category.finance
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        LSRequiresIPhoneOS: YES
        UILaunchScreen: ""
        UIApplicationSupportsIndirectInputEvents: YES
        UIApplicationSceneManifest: 
          UIApplicationSupportsMultipleScenes: YES
        UISupportedInterfaceOrientations~iphone:
          [UIInterfaceOrientationPortrait]
        UISupportedInterfaceOrientations~ipad:
          [UIInterfaceOrientationPortrait]