name: Router

options:
  groupSortPosition: "none"
  bundleIdPrefix: com.financial.control.router
  minimumXcodeGenVersion: 16.0
  generateEmptyDirectories: true
  plataform: iOS
  deploymentTarget:
    iOS: 18.0
    macOS: 15.0
    visionOS: 2.0
  postGenCommand: pod install

settings:
  base:
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    CODE_SIGN_STYLE: Automatic

targets:
  Router:
    type: framework
    platform: iOS
    deploymentTarget: "18.0"
    sources: 
      - Router
    settings:
      base:
        ENABLE_BITCODE: NO
        PRODUCT_BUNDLE_IDENTIFIER: com.financial.control.router.app
        PRODUCT_NAME: Router
    info:
      path: Router/Resources/Info.plist
      properties:
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        LSRequiresIPhoneOS: YES
        UIApplicationSupportsIndirectInputEvents: YES
        
  RouterSample:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources: 
      - RouterSample
    dependencies:
      - target: Router
    settings:
      base:
        ENABLE_BITCODE: NO
        PRODUCT_BUNDLE_IDENTIFIER: com.financial.control.app
        PRODUCT_NAME: RouterSample
        ENABLE_PREVIEWS: YES
        DEVELOPMENT_ASSET_PATHS: "\"RouterSample/Resources/Preview Content\""
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    info:
      path: RouterSample/Resources/Info.plist
      properties:
        UIStatusBarStyle: UIStatusBarStyleLightContent
        LSApplicationCategoryType: public.app-category.finance
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        LSRequiresIPhoneOS: YES
        UILaunchScreen: ""
        UIApplicationSupportsIndirectInputEvents: YES
        UIApplicationSceneManifest: 
          UIApplicationSupportsMultipleScenes: YES
        UISupportedInterfaceOrientations~iphone:
          [UIInterfaceOrientationPortrait]
        UISupportedInterfaceOrientations~ipad:
          [UIInterfaceOrientationPortrait]
