# Uncomment the next line to define a global platform for your project
 platform :ios, '18.0'

def router_pod
  #  pod 'Router', :git => 'https://github.com/TiagoLinharess/app-ios-financial-control-v2.git', :branch => 'main'
    pod 'Router', :path => '~/Documents/ProjetosPessoais/app-ios-financial-control-v2'
end

def internal_pods
  router_pod
end

def sharpnez_pods
#  pod 'SharpnezDesignSystemSwiftUI', :git => 'https://github.com/TiagoLinharess/sdk-ios-sharpnez-design-system.git', :tag => '2.1.0'
  pod 'SharpnezDesignSystemSwiftUI', :path => '~/Documents/ProjetosPessoais/sdk-ios-sharpnez-design-system'
end

target 'Home' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  sharpnez_pods
end

target 'HomeSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  internal_pods
  sharpnez_pods
end
