# Uncomment the next line to define a global platform for your project
 platform :ios, '18.0'

# pod 'Router', :path => '~/Documents/FinancialControl/app-ios-financial-control-v2'
# pod 'Router', :git => 'https://github.com/TiagoLinharess/app-ios-financial-control-v2.git', :branch => 'main'

def core_pod
   pod 'Core', :path => '~/Documents/FinancialControl/app-ios-financial-control-v2'
end

def router_pod
   pod 'Router', :path => '~/Documents/FinancialControl/app-ios-financial-control-v2'
end

def core_sample_pod
   pod 'CoreSample', :path => '~/Documents/FinancialControl/app-ios-financial-control-v2'
end

def internal_pods
  core_pod
  core_sample_pod
end

def sharpnez_pods
 pod 'SharpnezDesignSystemSwiftUI', :path => '~/Documents/Sharpnez/sdk-ios-sharpnez-design-system'
 pod 'SharpnezCore', :path => '~/Documents/Sharpnez/sdk-ios-sharpnez-core'
end

target 'Login' do
  use_frameworks!
  core_pod
  sharpnez_pods
end

target 'LoginSample' do
  use_frameworks!
  router_pod
  internal_pods
  sharpnez_pods
end
