# Uncomment the next line to define a global platform for your project
 platform :ios, '18.0'

# pod 'Router', :path => '~/Documents/ProjetosPessoais/app-ios-financial-control-v2'

 def router_pod
    pod 'Router', :path => '~/Documents/FinancialControl/app-ios-financial-control-v2'
 end

 def sample_pod
  pod 'Sample', :path => '~/Documents/FinancialControl/app-ios-financial-control-v2'
 end

 def provider_pod
  pod 'Provider', :path => '~/Documents/FinancialControl/app-ios-financial-control-v2'
 end

 def internal_pods
   provider_pod
   router_pod
 end

def snap_kit_pod
  pod 'SnapKit', '~> 5.7.1'
end

def keyboard_manager_pod
  pod 'IQKeyboardManagerSwift', '8.0.0'
end

def sharpnez_pods
 pod 'SharpnezDesignSystemUIKit', :path => '~/Documents/Sharpnez/sdk-ios-sharpnez-design-system'
 pod 'SharpnezCore', :path => '~/Documents/Sharpnez/sdk-ios-sharpnez-core'
 pod 'SharpnezCloud', :path => '~/Documents/Sharpnez/sdk-ios-sharpnez-cloud'
end

target 'Login' do
  use_frameworks!
  internal_pods
  keyboard_manager_pod
  snap_kit_pod
  sharpnez_pods
end

target 'LoginSample' do
  use_frameworks!
  internal_pods
  keyboard_manager_pod
  snap_kit_pod
  sharpnez_pods
  sample_pod
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      xcconfig_path = config.base_configuration_reference.real_path
      xcconfig = File.read(xcconfig_path)
      xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
      File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
    end
  end
end
