name: Login

options:
  groupSortPosition: "none"
  bundleIdPrefix: com.financial.control.login
  minimumXcodeGenVersion: 16.0
  generateEmptyDirectories: true
  plataform: iOS
  deploymentTarget: 18.0
  postGenCommand: pod install

settings:
  base:
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    CODE_SIGN_STYLE: Automatic

targets:
  Login:
    type: framework
    platform: iOS
    deploymentTarget: "18.0"
    sources: 
      - Login
    settings:
      base:
        ENABLE_BITCODE: NO
        PRODUCT_BUNDLE_IDENTIFIER: com.financial.control.login.app
        PRODUCT_NAME: Login
    info:
      path: Login/Resources/Info.plist
      properties:
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        LSRequiresIPhoneOS: YES
        UIApplicationSupportsIndirectInputEvents: YES
        
  LoginSample:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources: 
      - LoginSample
    dependencies:
      - target: Login
    settings:
      base:
        ENABLE_BITCODE: NO
        PRODUCT_BUNDLE_IDENTIFIER: com.financial.control.login.sample.app
        PRODUCT_NAME: LoginSample
        ENABLE_PREVIEWS: YES
        DEVELOPMENT_ASSET_PATHS: "\"LoginSample/Resources/Assets.xcassets\""
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    info:
      path: LoginSample/Resources/Info.plist
      properties:
        LSApplicationCategoryType: public.app-category.finance
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleAllowMixedLocalizations: YES
        LSRequiresIPhoneOS: YES
        UILaunchScreen: ""
        UIApplicationSupportsIndirectInputEvents: YES
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UISupportedInterfaceOrientations~iphone:
          [UIInterfaceOrientationPortrait]
        UISupportedInterfaceOrientations~ipad:
          [UIInterfaceOrientationPortrait]