# Uncomment the next line to define a global platform for your project
 platform :ios, '18.0'

# pod 'Router', :path => '~/Documents/ProjetosPessoais/app-ios-financial-control-v2'

def router_pod
   pod 'Router', :git => 'https://github.com/TiagoLinharess/app-ios-financial-control-v2.git', :branch => 'main'
end

def core_pod
   pod 'Core', :git => 'https://github.com/TiagoLinharess/app-ios-financial-control-v2.git', :branch => 'main'
end

def home_pod
   pod 'Home', :git => 'https://github.com/TiagoLinharess/app-ios-financial-control-v2.git', :branch => 'main'
end

def internal_pods
  core_pod
  home_pod
  router_pod
end

def sharpnez_pods
 pod 'SharpnezDesignSystemSwiftUI', :git => 'https://github.com/TiagoLinharess/sdk-ios-sharpnez-design-system.git', :tag => '2.2.0'
end

target 'FinancialControl' do
  use_frameworks!
  internal_pods
  sharpnez_pods
end
