# Uncomment the next line to define a global platform for your project
 platform :ios, '18.0'

def router_pod
   pod 'Router', :git => 'https://github.com/TiagoLinharess/app-ios-financial-control-v2.git', :branch => 'main'
end

def core_pod
   pod 'Core', :git => 'https://github.com/TiagoLinharess/app-ios-financial-control-v2.git', :branch => 'main'
end

def sharpnez_pods
 pod 'SharpnezDesignSystemSwiftUI', :git => 'https://github.com/TiagoLinharess/sdk-ios-sharpnez-design-system.git', :tag => '2.2.0'
end

target 'CoreSample' do
  use_frameworks!
  sharpnez_pods
  router_pod
  core_pod
end
