name: Core

options:
  groupSortPosition: "none"
  bundleIdPrefix: com.financial.control.core
  minimumXcodeGenVersion: 16.0
  generateEmptyDirectories: true
  plataform: iOS
  deploymentTarget:
    iOS: 18.0
    macOS: 15.0
    visionOS: 2.0
  postGenCommand: pod install

settings:
  base:
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    CODE_SIGN_STYLE: Automatic

targets:
  Core:
    type: framework
    platform: iOS
    deploymentTarget: "18.0"
    sources: 
        - Core
    settings:
      base:
        ENABLE_BITCODE: NO
        PRODUCT_BUNDLE_IDENTIFIER: com.financial.control.core.app
        PRODUCT_NAME: Core
    info:
      path: Core/Resources/Info.plist
      properties:
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        LSRequiresIPhoneOS: YES
        UIApplicationSupportsIndirectInputEvents: YES
