# Uncomment the next line to define a global platform for your project
 platform :ios, '18.0'

# def router_pod
#    pod 'Router', :git => 'https://github.com/TiagoLinharess/app-ios-financial-control-v2.git', :branch => 'main'
# end

def router_pod
   pod 'Router', :path => '~/Documents/FinancialControl/app-ios-financial-control-v2'
end

def sharpnez_pods
  pod 'SharpnezDesignSystemUIKit', :path => '~/Documents/Sharpnez/sdk-ios-sharpnez-design-system'
 end

target 'Sample' do
  use_frameworks!
  router_pod
  sharpnez_pods
end
