name: Sample

options:
  groupSortPosition: "none"
  bundleIdPrefix: com.financial.control.sample
  minimumXcodeGenVersion: 16.0
  generateEmptyDirectories: true
  plataform: iOS
  deploymentTarget:
    iOS: 18.0
    macOS: 15.0
    visionOS: 2.0
  postGenCommand: pod install

settings:
  base:
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    CODE_SIGN_STYLE: Automatic

targets:
  Sample:
    type: framework
    platform: iOS
    deploymentTarget: "18.0"
    sources: 
        - Sample
    settings:
      base:
        ENABLE_BITCODE: NO
        PRODUCT_BUNDLE_IDENTIFIER: com.financial.control.sample.app
        PRODUCT_NAME: Sample
    info:
      path: Sample/Resources/Info.plist
      properties:
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        LSRequiresIPhoneOS: YES
        UIApplicationSupportsIndirectInputEvents: YES
