name: Provider

options:
  groupSortPosition: "none"
  bundleIdPrefix: com.financial.control.provider
  minimumXcodeGenVersion: 16.0
  generateEmptyDirectories: true
  plataform: iOS
  deploymentTarget: 18.0
  postGenCommand: pod install

settings:
  base:
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    CODE_SIGN_STYLE: Automatic

targets:
  Provider:
    type: framework
    platform: iOS
    deploymentTarget: "18.0"
    sources: 
      - Provider
    settings:
      base:
        ENABLE_BITCODE: NO
        PRODUCT_BUNDLE_IDENTIFIER: com.financial.control.provier.app
        PRODUCT_NAME: Provider
    info:
      path: Provider/Resources/Info.plist
      properties:
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        LSRequiresIPhoneOS: YES
        UIApplicationSupportsIndirectInputEvents: YES